name: jams
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.0  
  json_serializable: ^6.5.4
  json_annotation: ^4.7.0
  build_runner: ^2.3.2
  rxdart: ^0.27.7
  flutter_bloc: ^8.0.0
  flutter_svg: ^1.1.6
  expandable_page_view: ^1.0.17
  rive: ^0.9.1
  google_fonts: ^3.0.1




dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/images/svgs/
    - assets/images/pngs/
    - assets/rive_assets/
